// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXn9cpMwQLJoJ2zDzefu-Ih4Uj7VD3rg',
    appId: '1:510649460404:web:dd8a37f8adb5b8147999e1',
    messagingSenderId: '510649460404',
    projectId: 'prexam-cf90d',
    authDomain: 'prexam-cf90d.firebaseapp.com',
    storageBucket: 'prexam-cf90d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TNgh1LGkjh1KhDS84UNErAkyM9h0vEM',
    appId: '1:510649460404:android:64a5abb1c90417a97999e1',
    messagingSenderId: '510649460404',
    projectId: 'prexam-cf90d',
    storageBucket: 'prexam-cf90d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdt--04nSe17Xyg17DnFCrhbeLe4U-Yr0',
    appId: '1:510649460404:ios:755f54488a56dd477999e1',
    messagingSenderId: '510649460404',
    projectId: 'prexam-cf90d',
    storageBucket: 'prexam-cf90d.firebasestorage.app',
    iosBundleId: 'com.example.prexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdt--04nSe17Xyg17DnFCrhbeLe4U-Yr0',
    appId: '1:510649460404:ios:755f54488a56dd477999e1',
    messagingSenderId: '510649460404',
    projectId: 'prexam-cf90d',
    storageBucket: 'prexam-cf90d.firebasestorage.app',
    iosBundleId: 'com.example.prexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvXn9cpMwQLJoJ2zDzefu-Ih4Uj7VD3rg',
    appId: '1:510649460404:web:4065c16b87d510067999e1',
    messagingSenderId: '510649460404',
    projectId: 'prexam-cf90d',
    authDomain: 'prexam-cf90d.firebaseapp.com',
    storageBucket: 'prexam-cf90d.firebasestorage.app',
  );
}
